CREATE TABLE Cargos(
CargoId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
NomeCargo VARCHAR(20) NOT NULL 
);

CREATE TABLE Usuario(
Email VARCHAR(255) PRIMARY KEY NOT NULL,
Senha VARCHAR(128) NOT NULL,
Nome VARCHAR(80) NOT NULL,
CargoId INT NOT NULL REFERENCES Cargos(CargoId)
);

CREATE TABLE EMPRESAS(
Cnpj VARCHAR(255) PRIMARY KEY NOT NULL,
RazaoSocial VARCHAR(80) NOT NULL,
DataCadastro DATETIME NOT NULL
);

CREATE TABLE TipoTarefas(
TipoTarefaId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
NomeTarefa VARCHAR(20) NOT NULL
);

CREATE TABLE Tarefa(
TarefaId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
HorarioInicio DATETIME NOT NULL,
HorarioFim DATETIME NOT NULL,
ResumoTarefa VARCHAR (80) NOT NULL,
DescricaoTarefa VARCHAR (255) NOT NULL,
Cnpj Varchar(255) NOT NULL REFERENCES Cnpj(Empresa),
TipoTarefaId INT NOT NULL REFERENCES TipoTarefas(TipoTarefaId)
);